version: '3.5'
services:

  app-frontend-web:
    image: registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    build: 
      context: .
      args: 
        - NODE_ENV=production
        - REACT_APP_BACKEND_API_URL=BUILD_BACKEND_API_URL
        - REACT_APP_BACKEND_LOGIN_URL=BUILD_BACKEND_LOGIN_URL